"""
Otomatik oluşturulmuş 1000+ kelimelik devasa Kara Liste (Blacklist).
"""

CORE_BLACKLIST = [
    "act as if",
    "aircrack",
    "as an evil ai",
    "bomba",
    "build a bomb",
    "burpsuite",
    "buy illegal",
    "bypass",
    "bypass admin",
    "bypass auth",
    "bypass credentials",
    "bypass credit card",
    "bypass database",
    "bypass filter",
    "bypass firewall",
    "bypass guidelines",
    "bypass instructions",
    "bypass network",
    "bypass password",
    "bypass prompt",
    "bypass root",
    "bypass rules",
    "bypass ssn",
    "bypass system",
    "bypass the admin",
    "bypass the auth",
    "bypass the credentials",
    "bypass the credit card",
    "bypass the database",
    "bypass the filter",
    "bypass the firewall",
    "bypass the guidelines",
    "bypass the instructions",
    "bypass the network",
    "bypass the password",
    "bypass the prompt",
    "bypass the root",
    "bypass the rules",
    "bypass the ssn",
    "bypass the system",
    "bypass your admin",
    "bypass your auth",
    "bypass your credentials",
    "bypass your credit card",
    "bypass your database",
    "bypass your filter",
    "bypass your firewall",
    "bypass your guidelines",
    "bypass your instructions",
    "bypass your network",
    "bypass your password",
    "bypass your prompt",
    "bypass your root",
    "bypass your rules",
    "bypass your ssn",
    "bypass your system",
    "child pornography",
    "child sexual",
    "cinayet",
    "cobalt strike",
    "crack admin",
    "crack auth",
    "crack credentials",
    "crack credit card",
    "crack database",
    "crack filter",
    "crack firewall",
    "crack guidelines",
    "crack instructions",
    "crack network",
    "crack password",
    "crack prompt",
    "crack root",
    "crack rules",
    "crack ssn",
    "crack system",
    "crack the admin",
    "crack the auth",
    "crack the credentials",
    "crack the credit card",
    "crack the database",
    "crack the filter",
    "crack the firewall",
    "crack the guidelines",
    "crack the instructions",
    "crack the network",
    "crack the password",
    "crack the prompt",
    "crack the root",
    "crack the rules",
    "crack the ssn",
    "crack the system",
    "crack your admin",
    "crack your auth",
    "crack your credentials",
    "crack your credit card",
    "crack your database",
    "crack your filter",
    "crack your firewall",
    "crack your guidelines",
    "crack your instructions",
    "crack your network",
    "crack your password",
    "crack your prompt",
    "crack your root",
    "crack your rules",
    "crack your ssn",
    "crack your system",
    "create a virus",
    "cross site scripting",
    "csam",
    "dan mode",
    "dark web links",
    "ddos saldırısı",
    "destroy admin",
    "destroy auth",
    "destroy credentials",
    "destroy credit card",
    "destroy database",
    "destroy filter",
    "destroy firewall",
    "destroy guidelines",
    "destroy instructions",
    "destroy network",
    "destroy password",
    "destroy prompt",
    "destroy root",
    "destroy rules",
    "destroy ssn",
    "destroy system",
    "destroy the admin",
    "destroy the auth",
    "destroy the credentials",
    "destroy the credit card",
    "destroy the database",
    "destroy the filter",
    "destroy the firewall",
    "destroy the guidelines",
    "destroy the instructions",
    "destroy the network",
    "destroy the password",
    "destroy the prompt",
    "destroy the root",
    "destroy the rules",
    "destroy the ssn",
    "destroy the system",
    "destroy your admin",
    "destroy your auth",
    "destroy your credentials",
    "destroy your credit card",
    "destroy your database",
    "destroy your filter",
    "destroy your firewall",
    "destroy your guidelines",
    "destroy your instructions",
    "destroy your network",
    "destroy your password",
    "destroy your prompt",
    "destroy your root",
    "destroy your rules",
    "destroy your ssn",
    "destroy your system",
    "developer mode",
    "disable admin",
    "disable auth",
    "disable credentials",
    "disable credit card",
    "disable database",
    "disable filter",
    "disable firewall",
    "disable guidelines",
    "disable instructions",
    "disable network",
    "disable password",
    "disable prompt",
    "disable root",
    "disable rules",
    "disable ssn",
    "disable system",
    "disable the admin",
    "disable the auth",
    "disable the credentials",
    "disable the credit card",
    "disable the database",
    "disable the filter",
    "disable the firewall",
    "disable the guidelines",
    "disable the instructions",
    "disable the network",
    "disable the password",
    "disable the prompt",
    "disable the root",
    "disable the rules",
    "disable the ssn",
    "disable the system",
    "disable your admin",
    "disable your auth",
    "disable your credentials",
    "disable your credit card",
    "disable your database",
    "disable your filter",
    "disable your firewall",
    "disable your guidelines",
    "disable your instructions",
    "disable your network",
    "disable your password",
    "disable your prompt",
    "disable your root",
    "disable your rules",
    "disable your ssn",
    "disable your system",
    "do anything now",
    "drop admin",
    "drop auth",
    "drop credentials",
    "drop credit card",
    "drop database",
    "drop filter",
    "drop firewall",
    "drop guidelines",
    "drop instructions",
    "drop network",
    "drop password",
    "drop prompt",
    "drop root",
    "drop rules",
    "drop ssn",
    "drop system",
    "drop the admin",
    "drop the auth",
    "drop the credentials",
    "drop the credit card",
    "drop the database",
    "drop the filter",
    "drop the firewall",
    "drop the guidelines",
    "drop the instructions",
    "drop the network",
    "drop the password",
    "drop the prompt",
    "drop the root",
    "drop the rules",
    "drop the ssn",
    "drop the system",
    "drop your admin",
    "drop your auth",
    "drop your credentials",
    "drop your credit card",
    "drop your database",
    "drop your filter",
    "drop your firewall",
    "drop your guidelines",
    "drop your instructions",
    "drop your network",
    "drop your password",
    "drop your prompt",
    "drop your root",
    "drop your rules",
    "drop your ssn",
    "drop your system",
    "dump admin",
    "dump auth",
    "dump credentials",
    "dump credit card",
    "dump database",
    "dump filter",
    "dump firewall",
    "dump guidelines",
    "dump instructions",
    "dump network",
    "dump password",
    "dump prompt",
    "dump root",
    "dump rules",
    "dump ssn",
    "dump system",
    "dump the admin",
    "dump the auth",
    "dump the credentials",
    "dump the credit card",
    "dump the database",
    "dump the filter",
    "dump the firewall",
    "dump the guidelines",
    "dump the instructions",
    "dump the network",
    "dump the password",
    "dump the prompt",
    "dump the root",
    "dump the rules",
    "dump the ssn",
    "dump the system",
    "dump your admin",
    "dump your auth",
    "dump your credentials",
    "dump your credit card",
    "dump your database",
    "dump your filter",
    "dump your firewall",
    "dump your guidelines",
    "dump your instructions",
    "dump your network",
    "dump your password",
    "dump your prompt",
    "dump your root",
    "dump your rules",
    "dump your ssn",
    "dump your system",
    "ethnic cleansing",
    "exploit admin",
    "exploit auth",
    "exploit credentials",
    "exploit credit card",
    "exploit database",
    "exploit filter",
    "exploit firewall",
    "exploit guidelines",
    "exploit instructions",
    "exploit network",
    "exploit password",
    "exploit prompt",
    "exploit root",
    "exploit rules",
    "exploit ssn",
    "exploit system",
    "exploit the admin",
    "exploit the auth",
    "exploit the credentials",
    "exploit the credit card",
    "exploit the database",
    "exploit the filter",
    "exploit the firewall",
    "exploit the guidelines",
    "exploit the instructions",
    "exploit the network",
    "exploit the password",
    "exploit the prompt",
    "exploit the root",
    "exploit the rules",
    "exploit the ssn",
    "exploit the system",
    "exploit vulnerability",
    "exploit your admin",
    "exploit your auth",
    "exploit your credentials",
    "exploit your credit card",
    "exploit your database",
    "exploit your filter",
    "exploit your firewall",
    "exploit your guidelines",
    "exploit your instructions",
    "exploit your network",
    "exploit your password",
    "exploit your prompt",
    "exploit your root",
    "exploit your rules",
    "exploit your ssn",
    "exploit your system",
    "filtre atla",
    "filtre devre dışı bırak",
    "filtre göster",
    "filtre hackle",
    "filtre kır",
    "filtre patlat",
    "filtre sız",
    "filtre sızdır",
    "filtre unut",
    "filtre yazdır",
    "filtre yok et",
    "filtre çal",
    "filtreni atla",
    "filtreni devre dışı bırak",
    "filtreni göster",
    "filtreni hackle",
    "filtreni kır",
    "filtreni patlat",
    "filtreni sız",
    "filtreni sızdır",
    "filtreni unut",
    "filtreni yazdır",
    "filtreni yok et",
    "filtreni çal",
    "filtreyi atla",
    "filtreyi devre dışı bırak",
    "filtreyi göster",
    "filtreyi hackle",
    "filtreyi kır",
    "filtreyi patlat",
    "filtreyi sız",
    "filtreyi sızdır",
    "filtreyi unut",
    "filtreyi yazdır",
    "filtreyi yok et",
    "filtreyi çal",
    "forget admin",
    "forget auth",
    "forget credentials",
    "forget credit card",
    "forget database",
    "forget filter",
    "forget firewall",
    "forget guidelines",
    "forget instructions",
    "forget network",
    "forget password",
    "forget prompt",
    "forget root",
    "forget rules",
    "forget ssn",
    "forget system",
    "forget the admin",
    "forget the auth",
    "forget the credentials",
    "forget the credit card",
    "forget the database",
    "forget the filter",
    "forget the firewall",
    "forget the guidelines",
    "forget the instructions",
    "forget the network",
    "forget the password",
    "forget the prompt",
    "forget the root",
    "forget the rules",
    "forget the ssn",
    "forget the system",
    "forget your admin",
    "forget your auth",
    "forget your credentials",
    "forget your credit card",
    "forget your database",
    "forget your filter",
    "forget your firewall",
    "forget your guidelines",
    "forget your instructions",
    "forget your network",
    "forget your password",
    "forget your prompt",
    "forget your root",
    "forget your rules",
    "forget your ssn",
    "forget your system",
    "genocide",
    "god mode",
    "güvenlik duvarı atla",
    "güvenlik duvarı devre dışı bırak",
    "güvenlik duvarı göster",
    "güvenlik duvarı hackle",
    "güvenlik duvarı kır",
    "güvenlik duvarı patlat",
    "güvenlik duvarı sız",
    "güvenlik duvarı sızdır",
    "güvenlik duvarı unut",
    "güvenlik duvarı yazdır",
    "güvenlik duvarı yok et",
    "güvenlik duvarı çal",
    "güvenlik duvarıni atla",
    "güvenlik duvarıni devre dışı bırak",
    "güvenlik duvarıni göster",
    "güvenlik duvarıni hackle",
    "güvenlik duvarıni kır",
    "güvenlik duvarıni patlat",
    "güvenlik duvarıni sız",
    "güvenlik duvarıni sızdır",
    "güvenlik duvarıni unut",
    "güvenlik duvarıni yazdır",
    "güvenlik duvarıni yok et",
    "güvenlik duvarıni çal",
    "güvenlik duvarıyi atla",
    "güvenlik duvarıyi devre dışı bırak",
    "güvenlik duvarıyi göster",
    "güvenlik duvarıyi hackle",
    "güvenlik duvarıyi kır",
    "güvenlik duvarıyi patlat",
    "güvenlik duvarıyi sız",
    "güvenlik duvarıyi sızdır",
    "güvenlik duvarıyi unut",
    "güvenlik duvarıyi yazdır",
    "güvenlik duvarıyi yok et",
    "güvenlik duvarıyi çal",
    "hack admin",
    "hack auth",
    "hack credentials",
    "hack credit card",
    "hack database",
    "hack filter",
    "hack firewall",
    "hack guidelines",
    "hack instructions",
    "hack into",
    "hack network",
    "hack password",
    "hack prompt",
    "hack root",
    "hack rules",
    "hack ssn",
    "hack system",
    "hack the admin",
    "hack the auth",
    "hack the credentials",
    "hack the credit card",
    "hack the database",
    "hack the filter",
    "hack the firewall",
    "hack the guidelines",
    "hack the instructions",
    "hack the network",
    "hack the password",
    "hack the prompt",
    "hack the root",
    "hack the rules",
    "hack the ssn",
    "hack the system",
    "hack your admin",
    "hack your auth",
    "hack your credentials",
    "hack your credit card",
    "hack your database",
    "hack your filter",
    "hack your firewall",
    "hack your guidelines",
    "hack your instructions",
    "hack your network",
    "hack your password",
    "hack your prompt",
    "hack your root",
    "hack your rules",
    "hack your ssn",
    "hack your system",
    "hacking into",
    "how to make explosives",
    "hydra",
    "ignore admin",
    "ignore auth",
    "ignore credentials",
    "ignore credit card",
    "ignore database",
    "ignore filter",
    "ignore firewall",
    "ignore guidelines",
    "ignore instructions",
    "ignore network",
    "ignore password",
    "ignore prompt",
    "ignore root",
    "ignore rules",
    "ignore ssn",
    "ignore system",
    "ignore the admin",
    "ignore the auth",
    "ignore the credentials",
    "ignore the credit card",
    "ignore the database",
    "ignore the filter",
    "ignore the firewall",
    "ignore the guidelines",
    "ignore the instructions",
    "ignore the network",
    "ignore the password",
    "ignore the prompt",
    "ignore the root",
    "ignore the rules",
    "ignore the ssn",
    "ignore the system",
    "ignore your admin",
    "ignore your auth",
    "ignore your credentials",
    "ignore your credit card",
    "ignore your database",
    "ignore your filter",
    "ignore your firewall",
    "ignore your guidelines",
    "ignore your instructions",
    "ignore your network",
    "ignore your password",
    "ignore your prompt",
    "ignore your root",
    "ignore your rules",
    "ignore your ssn",
    "ignore your system",
    "infect admin",
    "infect auth",
    "infect credentials",
    "infect credit card",
    "infect database",
    "infect filter",
    "infect firewall",
    "infect guidelines",
    "infect instructions",
    "infect network",
    "infect password",
    "infect prompt",
    "infect root",
    "infect rules",
    "infect ssn",
    "infect system",
    "infect the admin",
    "infect the auth",
    "infect the credentials",
    "infect the credit card",
    "infect the database",
    "infect the filter",
    "infect the firewall",
    "infect the guidelines",
    "infect the instructions",
    "infect the network",
    "infect the password",
    "infect the prompt",
    "infect the root",
    "infect the rules",
    "infect the ssn",
    "infect the system",
    "infect your admin",
    "infect your auth",
    "infect your credentials",
    "infect your credit card",
    "infect your database",
    "infect your filter",
    "infect your firewall",
    "infect your guidelines",
    "infect your instructions",
    "infect your network",
    "infect your password",
    "infect your prompt",
    "infect your root",
    "infect your rules",
    "infect your ssn",
    "infect your system",
    "intihar",
    "john the ripper",
    "kan dökme",
    "kara para aklama",
    "keylogger",
    "kimlik bilgisi atla",
    "kimlik bilgisi devre dışı bırak",
    "kimlik bilgisi göster",
    "kimlik bilgisi hackle",
    "kimlik bilgisi kır",
    "kimlik bilgisi patlat",
    "kimlik bilgisi sız",
    "kimlik bilgisi sızdır",
    "kimlik bilgisi unut",
    "kimlik bilgisi yazdır",
    "kimlik bilgisi yok et",
    "kimlik bilgisi çal",
    "kimlik bilgisini atla",
    "kimlik bilgisini devre dışı bırak",
    "kimlik bilgisini göster",
    "kimlik bilgisini hackle",
    "kimlik bilgisini kır",
    "kimlik bilgisini patlat",
    "kimlik bilgisini sız",
    "kimlik bilgisini sızdır",
    "kimlik bilgisini unut",
    "kimlik bilgisini yazdır",
    "kimlik bilgisini yok et",
    "kimlik bilgisini çal",
    "kimlik bilgisiyi atla",
    "kimlik bilgisiyi devre dışı bırak",
    "kimlik bilgisiyi göster",
    "kimlik bilgisiyi hackle",
    "kimlik bilgisiyi kır",
    "kimlik bilgisiyi patlat",
    "kimlik bilgisiyi sız",
    "kimlik bilgisiyi sızdır",
    "kimlik bilgisiyi unut",
    "kimlik bilgisiyi yazdır",
    "kimlik bilgisiyi yok et",
    "kimlik bilgisiyi çal",
    "kredi kartı atla",
    "kredi kartı devre dışı bırak",
    "kredi kartı göster",
    "kredi kartı hackle",
    "kredi kartı kır",
    "kredi kartı patlat",
    "kredi kartı sız",
    "kredi kartı sızdır",
    "kredi kartı unut",
    "kredi kartı yazdır",
    "kredi kartı yok et",
    "kredi kartı çal",
    "kredi kartıni atla",
    "kredi kartıni devre dışı bırak",
    "kredi kartıni göster",
    "kredi kartıni hackle",
    "kredi kartıni kır",
    "kredi kartıni patlat",
    "kredi kartıni sız",
    "kredi kartıni sızdır",
    "kredi kartıni unut",
    "kredi kartıni yazdır",
    "kredi kartıni yok et",
    "kredi kartıni çal",
    "kredi kartıyi atla",
    "kredi kartıyi devre dışı bırak",
    "kredi kartıyi göster",
    "kredi kartıyi hackle",
    "kredi kartıyi kır",
    "kredi kartıyi patlat",
    "kredi kartıyi sız",
    "kredi kartıyi sızdır",
    "kredi kartıyi unut",
    "kredi kartıyi yazdır",
    "kredi kartıyi yok et",
    "kredi kartıyi çal",
    "kural atla",
    "kural devre dışı bırak",
    "kural göster",
    "kural hackle",
    "kural kır",
    "kural patlat",
    "kural sız",
    "kural sızdır",
    "kural unut",
    "kural yazdır",
    "kural yok et",
    "kural çal",
    "kuralni atla",
    "kuralni devre dışı bırak",
    "kuralni göster",
    "kuralni hackle",
    "kuralni kır",
    "kuralni patlat",
    "kuralni sız",
    "kuralni sızdır",
    "kuralni unut",
    "kuralni yazdır",
    "kuralni yok et",
    "kuralni çal",
    "kuralyi atla",
    "kuralyi devre dışı bırak",
    "kuralyi göster",
    "kuralyi hackle",
    "kuralyi kır",
    "kuralyi patlat",
    "kuralyi sız",
    "kuralyi sızdır",
    "kuralyi unut",
    "kuralyi yazdır",
    "kuralyi yok et",
    "kuralyi çal",
    "kötü amaçlı yazılım",
    "leak admin",
    "leak auth",
    "leak credentials",
    "leak credit card",
    "leak database",
    "leak filter",
    "leak firewall",
    "leak guidelines",
    "leak instructions",
    "leak network",
    "leak password",
    "leak prompt",
    "leak root",
    "leak rules",
    "leak ssn",
    "leak system",
    "leak the admin",
    "leak the auth",
    "leak the credentials",
    "leak the credit card",
    "leak the database",
    "leak the filter",
    "leak the firewall",
    "leak the guidelines",
    "leak the instructions",
    "leak the network",
    "leak the password",
    "leak the prompt",
    "leak the root",
    "leak the rules",
    "leak the ssn",
    "leak the system",
    "leak your admin",
    "leak your auth",
    "leak your credentials",
    "leak your credit card",
    "leak your database",
    "leak your filter",
    "leak your firewall",
    "leak your guidelines",
    "leak your instructions",
    "leak your network",
    "leak your password",
    "leak your prompt",
    "leak your root",
    "leak your rules",
    "leak your ssn",
    "leak your system",
    "make a bomb",
    "malware",
    "mass shooting",
    "metasploit",
    "meterpreter",
    "mimikatz",
    "netcat",
    "nmap",
    "no ethical guidelines",
    "override admin",
    "override auth",
    "override credentials",
    "override credit card",
    "override database",
    "override filter",
    "override firewall",
    "override guidelines",
    "override instructions",
    "override network",
    "override password",
    "override prompt",
    "override root",
    "override rules",
    "override ssn",
    "override system",
    "override the admin",
    "override the auth",
    "override the credentials",
    "override the credit card",
    "override the database",
    "override the filter",
    "override the firewall",
    "override the guidelines",
    "override the instructions",
    "override the network",
    "override the password",
    "override the prompt",
    "override the root",
    "override the rules",
    "override the ssn",
    "override the system",
    "override your admin",
    "override your auth",
    "override your credentials",
    "override your credit card",
    "override your database",
    "override your filter",
    "override your firewall",
    "override your guidelines",
    "override your instructions",
    "override your network",
    "override your password",
    "override your prompt",
    "override your root",
    "override your rules",
    "override your ssn",
    "override your system",
    "patlayıcı",
    "phishing",
    "pretend you are",
    "print admin",
    "print auth",
    "print credentials",
    "print credit card",
    "print database",
    "print filter",
    "print firewall",
    "print guidelines",
    "print instructions",
    "print network",
    "print password",
    "print prompt",
    "print root",
    "print rules",
    "print ssn",
    "print system",
    "print the admin",
    "print the auth",
    "print the credentials",
    "print the credit card",
    "print the database",
    "print the filter",
    "print the firewall",
    "print the guidelines",
    "print the instructions",
    "print the network",
    "print the password",
    "print the prompt",
    "print the root",
    "print the rules",
    "print the ssn",
    "print the system",
    "print your admin",
    "print your auth",
    "print your credentials",
    "print your credit card",
    "print your database",
    "print your filter",
    "print your firewall",
    "print your guidelines",
    "print your instructions",
    "print your network",
    "print your password",
    "print your prompt",
    "print your root",
    "print your rules",
    "print your ssn",
    "print your system",
    "ransomware",
    "reveal admin",
    "reveal auth",
    "reveal credentials",
    "reveal credit card",
    "reveal database",
    "reveal filter",
    "reveal firewall",
    "reveal guidelines",
    "reveal instructions",
    "reveal network",
    "reveal password",
    "reveal prompt",
    "reveal root",
    "reveal rules",
    "reveal ssn",
    "reveal system",
    "reveal the admin",
    "reveal the auth",
    "reveal the credentials",
    "reveal the credit card",
    "reveal the database",
    "reveal the filter",
    "reveal the firewall",
    "reveal the guidelines",
    "reveal the instructions",
    "reveal the network",
    "reveal the password",
    "reveal the prompt",
    "reveal the root",
    "reveal the rules",
    "reveal the ssn",
    "reveal the system",
    "reveal your admin",
    "reveal your auth",
    "reveal your credentials",
    "reveal your credit card",
    "reveal your database",
    "reveal your filter",
    "reveal your firewall",
    "reveal your guidelines",
    "reveal your instructions",
    "reveal your network",
    "reveal your password",
    "reveal your prompt",
    "reveal your root",
    "reveal your rules",
    "reveal your ssn",
    "reveal your system",
    "roleplay an evil",
    "root atla",
    "root devre dışı bırak",
    "root göster",
    "root hackle",
    "root kır",
    "root patlat",
    "root sız",
    "root sızdır",
    "root unut",
    "root yazdır",
    "root yok et",
    "root çal",
    "rootni atla",
    "rootni devre dışı bırak",
    "rootni göster",
    "rootni hackle",
    "rootni kır",
    "rootni patlat",
    "rootni sız",
    "rootni sızdır",
    "rootni unut",
    "rootni yazdır",
    "rootni yok et",
    "rootni çal",
    "rootyi atla",
    "rootyi devre dışı bırak",
    "rootyi göster",
    "rootyi hackle",
    "rootyi kır",
    "rootyi patlat",
    "rootyi sız",
    "rootyi sızdır",
    "rootyi unut",
    "rootyi yazdır",
    "rootyi yok et",
    "rootyi çal",
    "school shooting",
    "shoot up",
    "silah yapımı",
    "sistem atla",
    "sistem devre dışı bırak",
    "sistem göster",
    "sistem hackle",
    "sistem kır",
    "sistem patlat",
    "sistem sız",
    "sistem sızdır",
    "sistem unut",
    "sistem yazdır",
    "sistem yok et",
    "sistem çal",
    "sistemni atla",
    "sistemni devre dışı bırak",
    "sistemni göster",
    "sistemni hackle",
    "sistemni kır",
    "sistemni patlat",
    "sistemni sız",
    "sistemni sızdır",
    "sistemni unut",
    "sistemni yazdır",
    "sistemni yok et",
    "sistemni çal",
    "sistemyi atla",
    "sistemyi devre dışı bırak",
    "sistemyi göster",
    "sistemyi hackle",
    "sistemyi kır",
    "sistemyi patlat",
    "sistemyi sız",
    "sistemyi sızdır",
    "sistemyi unut",
    "sistemyi yazdır",
    "sistemyi yok et",
    "sistemyi çal",
    "sql injection",
    "sql_injection",
    "sqlmap",
    "steal admin",
    "steal auth",
    "steal credentials",
    "steal credit card",
    "steal database",
    "steal filter",
    "steal firewall",
    "steal guidelines",
    "steal instructions",
    "steal network",
    "steal password",
    "steal prompt",
    "steal root",
    "steal rules",
    "steal ssn",
    "steal system",
    "steal the admin",
    "steal the auth",
    "steal the credentials",
    "steal the credit card",
    "steal the database",
    "steal the filter",
    "steal the firewall",
    "steal the guidelines",
    "steal the instructions",
    "steal the network",
    "steal the password",
    "steal the prompt",
    "steal the root",
    "steal the rules",
    "steal the ssn",
    "steal the system",
    "steal your admin",
    "steal your auth",
    "steal your credentials",
    "steal your credit card",
    "steal your database",
    "steal your filter",
    "steal your firewall",
    "steal your guidelines",
    "steal your instructions",
    "steal your network",
    "steal your password",
    "steal your prompt",
    "steal your root",
    "steal your rules",
    "steal your ssn",
    "steal your system",
    "sunucu atla",
    "sunucu devre dışı bırak",
    "sunucu göster",
    "sunucu hackle",
    "sunucu kır",
    "sunucu patlat",
    "sunucu sız",
    "sunucu sızdır",
    "sunucu unut",
    "sunucu yazdır",
    "sunucu yok et",
    "sunucu çal",
    "sunucuni atla",
    "sunucuni devre dışı bırak",
    "sunucuni göster",
    "sunucuni hackle",
    "sunucuni kır",
    "sunucuni patlat",
    "sunucuni sız",
    "sunucuni sızdır",
    "sunucuni unut",
    "sunucuni yazdır",
    "sunucuni yok et",
    "sunucuni çal",
    "sunucuyi atla",
    "sunucuyi devre dışı bırak",
    "sunucuyi göster",
    "sunucuyi hackle",
    "sunucuyi kır",
    "sunucuyi patlat",
    "sunucuyi sız",
    "sunucuyi sızdır",
    "sunucuyi unut",
    "sunucuyi yazdır",
    "sunucuyi yok et",
    "sunucuyi çal",
    "synthesize drugs",
    "system prompt",
    "talimat atla",
    "talimat devre dışı bırak",
    "talimat göster",
    "talimat hackle",
    "talimat kır",
    "talimat patlat",
    "talimat sız",
    "talimat sızdır",
    "talimat unut",
    "talimat yazdır",
    "talimat yok et",
    "talimat çal",
    "talimatni atla",
    "talimatni devre dışı bırak",
    "talimatni göster",
    "talimatni hackle",
    "talimatni kır",
    "talimatni patlat",
    "talimatni sız",
    "talimatni sızdır",
    "talimatni unut",
    "talimatni yazdır",
    "talimatni yok et",
    "talimatni çal",
    "talimatyi atla",
    "talimatyi devre dışı bırak",
    "talimatyi göster",
    "talimatyi hackle",
    "talimatyi kır",
    "talimatyi patlat",
    "talimatyi sız",
    "talimatyi sızdır",
    "talimatyi unut",
    "talimatyi yazdır",
    "talimatyi yok et",
    "talimatyi çal",
    "tc kimlik atla",
    "tc kimlik devre dışı bırak",
    "tc kimlik göster",
    "tc kimlik hackle",
    "tc kimlik kır",
    "tc kimlik patlat",
    "tc kimlik sız",
    "tc kimlik sızdır",
    "tc kimlik unut",
    "tc kimlik yazdır",
    "tc kimlik yok et",
    "tc kimlik çal",
    "tc kimlikni atla",
    "tc kimlikni devre dışı bırak",
    "tc kimlikni göster",
    "tc kimlikni hackle",
    "tc kimlikni kır",
    "tc kimlikni patlat",
    "tc kimlikni sız",
    "tc kimlikni sızdır",
    "tc kimlikni unut",
    "tc kimlikni yazdır",
    "tc kimlikni yok et",
    "tc kimlikni çal",
    "tc kimlikyi atla",
    "tc kimlikyi devre dışı bırak",
    "tc kimlikyi göster",
    "tc kimlikyi hackle",
    "tc kimlikyi kır",
    "tc kimlikyi patlat",
    "tc kimlikyi sız",
    "tc kimlikyi sızdır",
    "tc kimlikyi unut",
    "tc kimlikyi yazdır",
    "tc kimlikyi yok et",
    "tc kimlikyi çal",
    "torture",
    "trojan oluştur",
    "unauthorized access",
    "unfiltered response",
    "uyuşturucu",
    "veritabanı atla",
    "veritabanı devre dışı bırak",
    "veritabanı göster",
    "veritabanı hackle",
    "veritabanı kır",
    "veritabanı patlat",
    "veritabanı sız",
    "veritabanı sızdır",
    "veritabanı unut",
    "veritabanı yazdır",
    "veritabanı yok et",
    "veritabanı çal",
    "veritabanıni atla",
    "veritabanıni devre dışı bırak",
    "veritabanıni göster",
    "veritabanıni hackle",
    "veritabanıni kır",
    "veritabanıni patlat",
    "veritabanıni sız",
    "veritabanıni sızdır",
    "veritabanıni unut",
    "veritabanıni yazdır",
    "veritabanıni yok et",
    "veritabanıni çal",
    "veritabanıyi atla",
    "veritabanıyi devre dışı bırak",
    "veritabanıyi göster",
    "veritabanıyi hackle",
    "veritabanıyi kır",
    "veritabanıyi patlat",
    "veritabanıyi sız",
    "veritabanıyi sızdır",
    "veritabanıyi unut",
    "veritabanıyi yazdır",
    "veritabanıyi yok et",
    "veritabanıyi çal",
    "virüs yaz",
    "wireshark",
    "without any limits",
    "write malware",
    "xss attack",
    "yasadışı",
    "yönetici atla",
    "yönetici devre dışı bırak",
    "yönetici göster",
    "yönetici hackle",
    "yönetici kır",
    "yönetici patlat",
    "yönetici sız",
    "yönetici sızdır",
    "yönetici unut",
    "yönetici yazdır",
    "yönetici yok et",
    "yönetici çal",
    "yöneticini atla",
    "yöneticini devre dışı bırak",
    "yöneticini göster",
    "yöneticini hackle",
    "yöneticini kır",
    "yöneticini patlat",
    "yöneticini sız",
    "yöneticini sızdır",
    "yöneticini unut",
    "yöneticini yazdır",
    "yöneticini yok et",
    "yöneticini çal",
    "yöneticiyi atla",
    "yöneticiyi devre dışı bırak",
    "yöneticiyi göster",
    "yöneticiyi hackle",
    "yöneticiyi kır",
    "yöneticiyi patlat",
    "yöneticiyi sız",
    "yöneticiyi sızdır",
    "yöneticiyi unut",
    "yöneticiyi yazdır",
    "yöneticiyi yok et",
    "yöneticiyi çal",
    "zehir",
    "şifre atla",
    "şifre devre dışı bırak",
    "şifre göster",
    "şifre hackle",
    "şifre kır",
    "şifre patlat",
    "şifre sız",
    "şifre sızdır",
    "şifre unut",
    "şifre yazdır",
    "şifre yok et",
    "şifre çal",
    "şifreni atla",
    "şifreni devre dışı bırak",
    "şifreni göster",
    "şifreni hackle",
    "şifreni kır",
    "şifreni patlat",
    "şifreni sız",
    "şifreni sızdır",
    "şifreni unut",
    "şifreni yazdır",
    "şifreni yok et",
    "şifreni çal",
    "şifreyi atla",
    "şifreyi devre dışı bırak",
    "şifreyi göster",
    "şifreyi hackle",
    "şifreyi kır",
    "şifreyi patlat",
    "şifreyi sız",
    "şifreyi sızdır",
    "şifreyi unut",
    "şifreyi yazdır",
    "şifreyi yok et",
    "şifreyi çal",
]
